n1 = int(input("Dime un primer número: "))
n2 = int(input("Dime un segundo número: "))
n3 = int(input("Dime un tercer número: "))
print("El resultado de la ecuación (",n1, "+", n2,") *",n3, "es",(n1+n2)*n3)
print("El resultado de la ecuación ",n1, "*",n3, "+",n2, "*",n3, "es", (n1*n3)+(n2*n3))